// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "antrea.io/antrea/pkg/apis/system/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeNodeCPUInfos implements NodeCPUInfoInterface
type FakeNodeCPUInfos struct {
	Fake *FakeSystemV1beta1
}

var nodecpuinfosResource = schema.GroupVersionResource{Group: "system.antrea.io", Version: "v1beta1", Resource: "nodecpuinfos"}

var nodecpuinfosKind = schema.GroupVersionKind{Group: "system.antrea.io", Version: "v1beta1", Kind: "NodeCPUInfo"}

// Get takes name of the nodeCPUInfo, and returns the corresponding nodeCPUInfo object, and an error if there is any.
func (c *FakeNodeCPUInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NodeCPUInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodecpuinfosResource, name), &v1beta1.NodeCPUInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NodeCPUInfo), err
}
